name: covid_track_task
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.0.1
  easy_localization: 2.3.3+1
  google_fonts: ^1.1.0
  equatable: ^1.2.5
  awesome_dialog: ^1.2.1
  sqflite: ^1.3.1
  rxdart: ^0.23.1
  http:
  awesome_loader: ^0.0.3
  google_maps_flutter:
  geolocator: '^5.1.1'



dependency_overrides:
  intl: ^0.16.1
  path: 1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/


#  fonts:
#    - family: cairo
#      fonts:
#        - asset: fonts/Cairo/Cairo-Regular.ttf
#        - asset: fonts/Cairo/Cairo-Light.ttf
#        - asset: fonts/Cairo/Cairo-Black.ttf
#        - asset: fonts/Cairo/Cairo-Bold.ttf
#        - asset: fonts/Cairo/Cairo-SemiBold.ttf
